image: Ubuntu

stack: jdk 11
branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
<<<<<<< HEAD
  - ./gradlew test -Dselenide.headless=true
  - ./gradlew test --info
=======
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true --info
>>>>>>> second
